#-------------------------------
# General Site Settings
title: SpaceXplorer
logo: # You can add own logo. For example '/images/logo.png'.
description: SpaceXplorer is a project where the Unofficial SpaceX API is explored with Data Science.
baseurl: "" # The subpath of your site, e.g. /blog
url: "http://spacexplorer.com" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: 
  avatar: '/images/15.jpg'


#-------------------------------
# Hero Settings
hero:
  title: SpaceXplorer
  description: Explore the Unofficial SpaceX API with Data Science.
  image: '/images/01.jpg'


#-------------------------------
# Contact Settings
contact:
  email: renato.gusani@outlook.com # Add your email for contant form
  description: Hello! Get in contact with me by filing in the below form, whether you would like to say hello or open up a dialogue, I am here! # Add a description of your form

# NOTE
# Aditu theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
social:
#- {icon: "ion-logo-twitter", link: "https://twitter.com"}
#- {icon: "ion-logo-facebook", link: "https://facebook.com"}
#- {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
#- {icon: "ion-logo-instagram", link: "https://instagram.com"}
#- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
- {icon: "ion-logo-github", link: "https://github.com/renatogusani"}
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/rgusani/"}
- {icon: "ion-logo-person-sharp", link: "https://www.renatogusani.github.io/"}

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: Reno # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: true # To enable the mailchimp form, use the value true. To turn off use the value false.
mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
